# netlify.toml — Munna Coded

[build]
  publish = "."

# --------------------------
# Pretty URL rewrites (200)
# --------------------------
[[redirects]]
  from = "/about"
  to   = "/pages/about.html"
  status = 200

[[redirects]]
  from = "/projects"
  to   = "/pages/projects.html"
  status = 200

[[redirects]]
  from = "/projects/alokchhaya-high-school"
  to   = "/pages/projects/alokchhaya-high-school.html"
  status = 200

[[redirects]]
  from = "/skills"
  to   = "/pages/skills.html"
  status = 200

[[redirects]]
  from = "/testimonials"
  to   = "/pages/testimonials.html"
  status = 200

[[redirects]]
  from = "/contact"
  to   = "/pages/contact.html"
  status = 200

[[redirects]]
  from = "/thanks"
  to   = "/pages/thanks.html"
  status = 200

# -----------------------------------
# Canonical redirects (file → pretty)
# -----------------------------------
[[redirects]]
  from = "/index.html"
  to   = "/"
  status = 301
  force = true

[[redirects]]
  from = "/pages/about.html"
  to   = "/about"
  status = 301

[[redirects]]
  from = "/pages/projects.html"
  to   = "/projects"
  status = 301

[[redirects]]
  from = "/pages/projects/alokchhaya-high-school.html"
  to   = "/projects/alokchhaya-high-school"
  status = 301

[[redirects]]
  from = "/pages/skills.html"
  to   = "/skills"
  status = 301

[[redirects]]
  from = "/pages/testimonials.html"
  to   = "/testimonials"
  status = 301

[[redirects]]
  from = "/pages/contact.html"
  to   = "/contact"
  status = 301

[[redirects]]
  from = "/pages/thanks.html"
  to   = "/thanks"
  status = 301


# ----------------
# Security headers
# ----------------
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

# HTML: avoid caching pages
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

# Long-term cache for static assets
[[headers]]
  for = "/assets/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/img/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/favicons/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# sitemap/robots content-type + caching
[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml; charset=utf-8"
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/sitemap.txt"
  [headers.values]
    Content-Type = "text/plain; charset=utf-8"
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain; charset=utf-8"
    Cache-Control = "public, max-age=86400"

# Thanks page: ensure noindex via header (meta already set)
[[headers]]
  for = "/thanks"
  [headers.values]
    X-Robots-Tag = "noindex, follow"

[[headers]]
  for = "/pages/thanks.html"
  [headers.values]
    X-Robots-Tag = "noindex, follow"

# Optional CSP (enable only after whitelisting external CDNs)
# [[headers]]
#   for = "/*"
#   [headers.values]
#     Content-Security-Policy = "default-src 'self'; img-src 'self' data: https:; script-src 'self' https://cdnjs.cloudflare.com https://fonts.googleapis.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdnjs.cloudflare.com; font-src 'self' https://fonts.gstatic.com https://cdnjs.cloudflare.com; connect-src 'self';"